#如果您还没有注册服务器账号请打开官网注册账号获得SID和Key信息
#官网: https://vexrmb.i8mc.cn
#MCBBS介绍帖：http://www.mcbbs.net/thread-857710-1-1.html
#网站控制台的左侧找到：“我的服务器”，点击后在右侧的 “我旗下的服务器” 栏目中找到你的服务器信息
#找到SID(编号)、KEY(密钥)两项，填入即可
SID: 2855
#服务器Key
Key: c9wvJZBlOeRidwrC
#填写示范：
#SID:(空格)123
#Key:(空格)abcdefghijklmn

#检查更新
checkUpdate: false

#设置主命令
Cmd: 'vexrmb'

#Time 自动检测时间, 每隔多少分钟检测一次(单位: 分钟)
#推荐如果要设置就设置30分钟以上，请勿调至过低，会造成服务器卡顿
#设置为0或以下 即为关闭
Time: 0

#手动检查冷却, 有自动到账 不建议使用自动检查 (单位: 分钟)
#手动可以让玩家自己使用命令检查到账
#如果开自动 就不要给玩家手动的权限
CheckTime: 5

#支付方式，设置后将会转换为变量{2}
payway:
  qq: '§f§lQQ'
  alipay: '§b§l支付宝'
  wechat: '§a§l微信'

#commands 给予点券的命令
#{0}代表玩家
#{1}代表金额
#注意{0}和{1}是变量，跟费率无关！千万别傻乎乎的填成{10} {100}！
commands:
  #给予玩家对应的点券,充多少给多少
  - 'eco add {0} {1}'
#指令示范
#给予玩家对应的钻石,充多少给多少 [删除#号启用,不删除则不启用]
#- 'give {0} 264 {1}'
#给予玩家100倍的金币,充多少给多少 [删除#号启用,不删除则不启用]
#- 'eco give {0} {1}00'
#向玩家发送一个json大标题 [删除#号启用,不删除则不启用]
#- 'title {0} title {"text":"感谢支持服务器!","color":"red"}'
#向全服玩家发送一个ess的bc公告 [删除#号启用,不删除则不启用]
#- 'bc 玩家{0}充值了{1}，服务器感谢Ta的大力支持!'
#注: 上方指令支持PlaceholderAPI变量

#{0}代表玩家
#{1}代表金额
#{2}代表充值方式
openCommands:
  - 'title {0} title ["",{"text":"\u8bf7\u6253\u5f00","bold":true,"color":"gold"},{"text":"{2}","bold":true},{"text":"\u626b\u7801\u5145\u503c","bold":true,"color":"gold"}]'
  #当打开二维码地图时执行的指令(支持PlaceholderAPI变量)

#自定义支付地图的物品名称及描述 然而并没有用
map:
  display: '§a§l扫码地图'
  lore:
    - '§7· 请扫描地图上的二维码'
    - '§7· 支付完成后服务器'
    - '§7· 会在1-2分钟后自动发货'